version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
  app:
    build: ./
    container_name: backend_api
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    command: sh -c "sleep 10 && npm run start"
  redis:
    image: redis:6.2.5-alpine
    environment:
      REDIS_URL: ${REDIS_URL}
