version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
  app:
    image: cloud-bs
    ports:
      - '13000:8000'
    depends_on:
      - db
    command: sh -c "sleep 10 && npm run start"
